/* file generated by nits for module sdl */
/* TODO: rename this file to sdl.nit.c and implement the following methods. */



#include "sdl.nit.h"

/*
C implementation of sdl::SDLDisplay::init
*/
SDLDisplay new_SDLDisplay___impl( long int w, long int h )
{
	SDL_Init(SDL_INIT_VIDEO);
	
	if(TTF_Init()==-1) {
		printf("TTF_Init: %s\n", TTF_GetError());
		exit(2);
	}
	
	/* ignores mousemotion for performance reasons */
	SDL_EventState( SDL_MOUSEMOTION, SDL_IGNORE );
	
	return SDL_SetVideoMode( w, h, 24, SDL_HWSURFACE );
}

/*
C implementation of sdl::SDLDisplay::destroy
*/
void SDLDisplay_destroy___impl( SDLDisplay recv )
{
	if ( SDL_WasInit( SDL_INIT_VIDEO ) )
		SDL_Quit();
		
	if ( TTF_WasInit() )
		TTF_Quit();
}

/*
C implementation of sdl::SDLDisplay::flip
*/
void SDLDisplay_flip___impl( SDLDisplay recv )
{
	SDL_Flip( recv );
}

/*
C implementation of sdl::SDLDisplay::blit
*/
void SDLDisplay_blit___impl( SDLDisplay recv, Image img, long int x, long int y )
{
	SDL_Rect dst; /* [ x, y, 0, 0 ); */
	dst.x = x;
	dst.y = y;
	dst.w = 0;
	dst.h = 0;

	SDL_BlitSurface( img, NULL, recv, &dst );
}

void SDLDisplay_clear___impl( SDLDisplay recv, long int r, long int g, long int b )
{
    SDL_FillRect( recv, NULL, SDL_MapRGB(recv->format,r,g,b) ); 
}

/*
C implementation of sdl::SDLDisplay::width
*/
long int SDLDisplay_width___impl( SDLDisplay recv )
{
	return recv->w;
}

/*
C implementation of sdl::SDLDisplay::height
*/
long int SDLDisplay_height___impl( SDLDisplay recv )
{
	return recv->h;
}

/*
C implementation of sdl::SDLDisplay::fill_rect
*/
void SDLDisplay_fill_rect___impl( SDLDisplay recv, Rectangle rect, long int r, long int g, long int b )
{
	SDL_FillRect( recv, rect,  SDL_MapRGB(recv->format,r,g,b) );
}

/*
C implementation of sdl::SDLDisplay::poll_event

Imported methods signatures:
	KeyboardEvent new_KeyboardEvent( String key_name, int down ) for sdl::KeyboardEvent::init
	MouseEvent new_MouseEvent( long int x, long int y, long int button, int down ) for sdl::MouseEvent::init for sdl::MouseEvent::init
	String new_String_from_cstring( char* str ) for string::String::from_cstring
*/
nullable_Event SDLDisplay_poll_event___impl( SDLDisplay recv )
{
    SDL_Event event;
    
	SDL_PumpEvents();

    if ( SDL_PollEvent(&event) )
SDL_EventState( SDL_MOUSEMOTION, SDL_IGNORE );
    {
        switch (event.type ) {
		    case SDL_KEYDOWN:
			case SDL_KEYUP:
#ifdef DEBUG
		        printf("The \"%s\" key was pressed!\n",
		               SDL_GetKeyName(event.key.keysym.sym));
#endif
		               
				return KeyboardEvent_as_nullable_Event( new_KeyboardEvent( new_String_from_cstring( SDL_GetKeyName(event.key.keysym.sym) ),
										  event.type==SDL_KEYDOWN ) );
			
		/*	case SDL_MOUSEMOTION:
				printf("Mouse moved by %d,%d to (%d,%d)\n", 
					   event.motion.xrel, event.motion.yrel,
					   event.motion.x, event.motion.y);*/
			
			case SDL_MOUSEBUTTONDOWN:
			case SDL_MOUSEBUTTONUP:
#ifdef DEBUG
				printf("Mouse button \"%d\" pressed at (%d,%d)\n",
					   event.button.button, event.button.x, event.button.y);
#endif
				return MouseEvent_as_nullable_Event( new_MouseEvent( event.button.x, event.button.y, 
									   event.button.button,
									   event.type == SDL_MOUSEBUTTONDOWN ) );
			
			case SDL_QUIT:
				break;
        }
    }
    
    return null_Event();
}

/*
C implementation of sdl::SDLDisplay::spacebar_is_pressed
*/
int SDLDisplay_spacebar_is_pressed___impl( SDLDisplay recv )
{
    SDL_Event event;

    while ( SDL_PollEvent(&event) ) {
        switch (event.type) {
        case SDL_KEYDOWN:
            printf("The %s key was pressed!\n",
                   SDL_GetKeyName(event.key.keysym.sym));
                   if ( event.key.keysym.sym == SDLK_SPACE )
                   	  return true;
            break;
        }
    }
    return false;
}

/*
C implementation of sdl::Image::from_file

Imported methods signatures:
	char* String_to_cstring( String recv ) for string::String::to_cstring
*/
Image new_Image_from_file___impl( String path )
{
	SDL_Surface *image = IMG_Load( String_to_cstring( path ) );
	return image;
}

/*
C implementation of sdl::Image::partial
*/
Image new_Image_partial___impl( Image original, Rectangle clip )
{
	return NULL;
}

/*
C implementation of sdl::Image::copy_of
*/
Image new_Image_copy_of___impl( Image image )
{
	SDL_Surface *new_image = SDL_CreateRGBSurface( image->flags, image->w, image->h, 24,
						  0, 0, 0, 0 );
	/*SDL_Surface *new_image = (SDL_Surface*)malloc(sizeof(SDL_Surface));
	memcpy(new_image, image, sizeof(SDL_Surface));
	new_image->refcount++;*/
	
	SDL_Rect dst; /* [ x, y, 0, 0 ); */
	dst.x = 0;
	dst.y = 0;
	dst.w = image->w;
	dst.h = image->h;
	SDL_BlitSurface( image, NULL, new_image, &dst );
	
	return new_image;
}

/*
C implementation of sdl::Image::init
*//*
Image new_Image___impl( long int w, long int h )
{
	SDL_CreateRGBSurface( 0, w, h, 24 );
}*/

/*
C implementation of sdl::Image::blit
*/
void Image_blit___impl( Image recv, Image img, long int x, long int y )
{
	SDL_Rect dst; /* [ x, y, 0, 0 ); */
	dst.x = x;
	dst.y = y;
	dst.w = 0;
	dst.h = 0;

	SDL_BlitSurface( img, NULL, recv, &dst );
}

/*
C implementation of sdl::Image::save_to_file

Imported methods signatures:
	char* String_to_cstring( String recv ) for string::String::to_cstring
*/
void Image_save_to_file___impl( Image recv, String path )
{
}

/*
C implementation of sdl::Image::clear
*/
void Image_clear___impl( Image recv, float c )
{
}

/*
C implementation of sdl::Image::destroy
*/
void Image_destroy___impl( Image recv )
{
	SDL_FreeSurface( recv );
}

/*
C implementation of sdl::Image::width
*/
long int Image_width___impl( Image recv )
{
	return recv->w;
}

/*
C implementation of sdl::Image::height
*/
long int Image_height___impl( Image recv )
{
	return recv->h;
}

/*
C implementation of sdl::Rectangle::init
*/
Rectangle new_Rectangle___impl( long int x, long int y, long int w, long int h )
{
	SDL_Rect *rect = malloc( sizeof( SDL_Rect ) );
	rect->x = (Sint16)x;
	rect->y = (Sint16)y;
	rect->w = (Uint16)w;
	rect->h = (Uint16)h;
	return rect;
}

/*
C implementation of sdl::Rectangle::x=
*/
void Rectangle_x__assign___impl( Rectangle recv, long int v )
{
	recv->x = (Sint16)v;
}

/*
C implementation of sdl::Rectangle::x
*/
long int Rectangle_x___impl( Rectangle recv )
{
	return recv->x;
}

/*
C implementation of sdl::Rectangle::y=
*/
void Rectangle_y__assign___impl( Rectangle recv, long int v )
{
	recv->y = (Sint16)v;
}

/*
C implementation of sdl::Rectangle::y
*/
long int Rectangle_y___impl( Rectangle recv )
{
	return recv->y;
}

/*
C implementation of sdl::Rectangle::w=
*/
void Rectangle_w__assign___impl( Rectangle recv, long int v )
{
	recv->w = (Uint16)v;
}

/*
C implementation of sdl::Rectangle::w
*/
long int Rectangle_w___impl( Rectangle recv )
{
	return recv->w;
}

/*
C implementation of sdl::Rectangle::h=
*/
void Rectangle_h__assign___impl( Rectangle recv, long int v )
{
	recv->h = (Uint16)v;
}

/*
C implementation of sdl::Rectangle::h
*/
long int Rectangle_h___impl( Rectangle recv )
{
	return recv->h;
}

/*
C implementation of sdl::Rectangle::destroy
*/
void Rectangle_destroy___impl( Rectangle recv )
{
}

/*
C implementation of sdl::Int::delay
*/
void Int_delay___impl( bigint recv )
{
	SDL_Delay( recv );
}

/*
C implementation of sdl::Font::init

Imported methods signatures:
	char * String__to_cstring( String recv ) for string::String::to_cstring
*/
Font new_Font___impl( String name, bigint points )
{
	char * cname = String_to_cstring( name );
	
	Font font = TTF_OpenFont( cname, (int)points);
	if(!font) {
		printf("TTF_OpenFont: %s\n", TTF_GetError());
		exit( 1 );
	}
	
	return font;
}

/*
C implementation of sdl::Font::destroy
*/
void Font_destroy___impl( Font recv )
{
	TTF_CloseFont( recv );
}

/*
C implementation of sdl::Font::render

Imported methods signatures:
	char * String__to_cstring( String recv ) for string::String::to_cstring
*/
Image Font_render___impl( Font recv, String text, bigint r, bigint g, bigint b )
{
	SDL_Color color;
	SDL_Surface *text_surface;
	char *ctext;
	
	/*color = SDL_MapRGB(NULL,r,g,b);*/
	color.r = r;
	color.g = g;
	color.b = b;
	
	ctext = String_to_cstring( text );
	if( !(text_surface=TTF_RenderText_Blended( recv, ctext, color )) )
	{
		fprintf( stderr, "SDL TFF error: %s\n", TTF_GetError() );
		exit( 1 );
	}
	else
		return text_surface;
}

#if SDL_TTF_MAJOR_VERSION >= 2 && ( SDL_TTF_MAJOR_VERSION > 2 || SDL_TTF_MINOR_VERSION > 0 || SDL_TTF_PATCHLEVEL > 9 )
	
/*
C implementation of sdl::Font::outline
*/
bigint Font_outline___impl( Font recv )
{
	return TTF_GetFontOutline( recv );
}

/*
C implementation of sdl::Font::outline=
*/
void Font_outline__assign___impl( Font recv, bigint v )
{
	TTF_SetFontOutline( recv, v );
}

/*
C implementation of sdl::Font::kerning
*/
int Font_kerning___impl( Font recv )
{
	return TTF_GetFontKerning( recv );
}

/*
C implementation of sdl::Font::kerning=
*/
void Font_kerning__assign___impl( Font recv, int v )
{
	TTF_SetFontKerning( recv, v );
}
#endif

/*
C implementation of sdl::Font::height
*/
bigint Font_height___impl( Font recv )
{
	return TTF_FontHeight( recv );
}

/*
C implementation of sdl::Font::ascent
*/
bigint Font_ascent___impl( Font recv )
{
	return TTF_FontAscent( recv );
}

/*
C implementation of sdl::Font::descent
*/
bigint Font_descent___impl( Font recv )
{
	return TTF_FontDescent( recv );
}

/*
C implementation of sdl::Font::line_skip
*/
bigint Font_line_skip___impl( Font recv )
{
	return TTF_FontLineSkip( recv );
}

/*
C implementation of sdl::Font::is_fixed_width
*/
int Font_is_fixed_width___impl( Font recv )
{
	return TTF_FontFaceIsFixedWidth( recv );
}

/*
C implementation of sdl::Font::family_name

Imported methods signatures:
	char * String_to_cstring( String recv ) for string::String::to_cstring
	nullable_String String_as_nullable( String value ) to cast from String to nullable String
*/
nullable_String Font_family_name___impl( Font recv )
{
	char *fn = TTF_FontFaceFamilyName( recv );
	
	if ( fn == NULL )
		return null_String();
	else
		return String_as_nullable( new_String_from_cstring( fn ) );
}

/*
C implementation of sdl::Font::style_name

Imported methods signatures:
	char * String_to_cstring( String recv ) for string::String::to_cstring
	nullable_String String_as_nullable( String value ) to cast from String to nullable String
*/
nullable_String Font_style_name___impl( Font recv )
{
	char *sn = TTF_FontFaceStyleName( recv );
	
	if ( sn == NULL )
		return null_String();
	else
		return String_as_nullable( new_String_from_cstring( sn ) );
}

/*
C implementation of sdl::Font::width_of

Imported methods signatures:
	String new_String_from_cstring( char * str ) for string::String::from_cstring
*/
bigint Font_width_of___impl( Font recv, String text )
{
	char *ctext = String_to_cstring( text );
	int w;
	if ( TTF_SizeText( recv, ctext, &w, NULL ) )
	{
		fprintf( stderr, "SDL TFF error: %s\n", TTF_GetError() );
		exit( 1 );
	}
	else
		return w;
}

