/* file generated by nits for module sdl */
/* TODO: rename this file to sdl.nit.h and implement the following methods. */

#ifndef sdl_IMPL_NIT_H
#define sdl_IMPL_NIT_H

#include <SDL/SDL.h>
#include <SDL/SDL_image.h>

#define SDLDisplay SDL_Surface*
#define Image SDL_Surface*
#define Rectangle SDL_Rect*

#include <sdl._nitni.h>
#include <nit_common.h>

SDLDisplay new_SDLDisplay___impl( long int w, long int h );
void SDLDisplay_destroy___impl( SDLDisplay recv );
void SDLDisplay_flip___impl( SDLDisplay recv );
void SDLDisplay_blit___impl( SDLDisplay recv, Image img, bigint x, bigint y );
void SDLDisplay_clear___impl( SDLDisplay recv, long int r, long int g, long int b );
bigint SDLDisplay_width___impl( SDLDisplay recv );
bigint SDLDisplay_height___impl( SDLDisplay recv );
nullable_Event SDLDisplay_poll_event___impl( SDLDisplay recv );
int SDLDisplay_spacebar_is_pressed___impl( SDLDisplay recv );
Image new_Image_from_file___impl( String path );
Image new_Image_partial___impl( Image original, Rectangle clip );
Image new_Image_copy_of___impl( Image image );
void Image_blit___impl( Image recv, Image img, bigint x, bigint y );
void Image_save_to_file___impl( Image recv, String path );
void Image_clear___impl( Image recv, float c );
void Image_destroy___impl( Image recv );
bigint Image_width___impl( Image recv );
bigint Image_height___impl( Image recv );
Rectangle new_Rectangle___impl( bigint x, bigint y, bigint w, bigint h );
void Rectangle_x__eq___impl( Rectangle recv, bigint v );
bigint Rectangle_x___impl( Rectangle recv );
void Rectangle_y__eq___impl( Rectangle recv, bigint v );
bigint Rectangle_y___impl( Rectangle recv );
void Rectangle_w__eq___impl( Rectangle recv, bigint v );
bigint Rectangle_w___impl( Rectangle recv );
void Rectangle_h__eq___impl( Rectangle recv, bigint v );
bigint Rectangle_h___impl( Rectangle recv );
void Rectangle_destroy___impl( Rectangle recv );

#endif
